# Generated by Django 6.0.3 on 2026-03-24 18:51

import content.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ky', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'document categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='representatives/')),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_ky', models.CharField(max_length=255)),
                ('role_ru', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('role_ky', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ky', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ky', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
            ],
            options={
                'ordering': ['deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ky', models.CharField(max_length=255)),
                ('file_ru', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), content.models.validate_pdf])),
                ('file_en', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), content.models.validate_pdf])),
                ('file_ky', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), content.models.validate_pdf])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='content.documentcategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
